import React from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Card, Title, Paragraph, DataTable, Divider } from 'react-native-paper';
import { useRoute } from '@react-navigation/native';

// Detailed Report Screen
const DetailedReportScreen = () => {
  const route = useRoute();
  const { jeepData, totalRevenue, totalBookings, seatOccupancyRate } = route.params;

  return (
    <ScrollView style={styles.container}>
      {/* Detailed Report Header */}
      <Card style={styles.card}>
        <Card.Content>
          <Title style={styles.title}>Detailed Revenue Report</Title>
          <Paragraph style={styles.date}>Date: November 26, 2024</Paragraph>
        </Card.Content>
      </Card>

      {/* Total Revenue Section */}
      <Card style={styles.card}>
        <Card.Content>
          <Title style={styles.sectionTitle}>Summary</Title>
          <Paragraph>Total Revenue: <Text style={styles.highlightText}>₱{totalRevenue}</Text></Paragraph>
          <Paragraph>Total Number of Bookings: {totalBookings}</Paragraph>
          <Paragraph>Seat Occupancy Rate: {seatOccupancyRate}%</Paragraph>
        </Card.Content>
      </Card>

      {/* Detailed Revenue Breakdown */}
      <Card style={styles.card}>
        <Card.Content>
          <Title style={styles.sectionTitle}>Detailed Revenue Breakdown</Title>
          <DataTable>
            <DataTable.Header>
              <DataTable.Title>Jeep ID</DataTable.Title>
              <DataTable.Title>Route</DataTable.Title>
              <DataTable.Title numeric>Seats Booked</DataTable.Title>
              <DataTable.Title numeric>Revenue (₱)</DataTable.Title>
            </DataTable.Header>

            {jeepData.map((jeep) => (
              <DataTable.Row key={jeep.id}>
                <DataTable.Cell>{jeep.id}</DataTable.Cell>
                <DataTable.Cell>{jeep.route}</DataTable.Cell>
                <DataTable.Cell numeric>{jeep.seatsBooked}</DataTable.Cell>
                <DataTable.Cell numeric>{jeep.revenue}</DataTable.Cell>
              </DataTable.Row>
            ))}
          </DataTable>
        </Card.Content>
      </Card>

      {/* Footer Section */}
      <Divider style={styles.divider} />
      <Text style={styles.footer}>Report generated by Jeepney Reservation System</Text>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4f4f4',
    paddingTop: 20,
  },
  card: {
    marginHorizontal: 15,
    marginBottom: 20,
    borderRadius: 10,
    backgroundColor: '#fff',
    elevation: 3,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#333',
  },
  date: {
    fontSize: 16,
    color: '#666',
    marginTop: 5,
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: '600',
    color: '#333',
    marginBottom: 10,
  },
  highlightText: {
    color: '#6200ea',
    fontWeight: 'bold',
  },
  footer: {
    fontSize: 14,
    textAlign: 'center',
    color: '#888',
    paddingVertical: 10,
  },
  divider: {
    marginVertical: 15,
    marginHorizontal: 20,
    backgroundColor: '#ccc',
  },
});

export default DetailedReportScreen;
